subconsciousnetwork/noosphere

README.md

Small changes to README intro language. WDYT?

Update readme intro pitch

---

rust/README.md

Adding README to /rust

---

design/principles.md

This PR contains the same content as #81 but the commit is signed.
Fixes https://github.com/subconsciousnetwork/noosphere/issues/79.

Add principles doc

---

rust/noosphere-fs/src/fs.rs

Follow-up cleanup of https://github.com/subconsciousnetwork/noosphere/pull/89

Refactor `if` statement in SphereFs::save

---

rust/noosphere-ns/src/builder.rs
rust/noosphere-ns/src/dht/config.rs
rust/noosphere-ns/src/dht/swarm.rs
rust/noosphere-ns/src/name_system.rs
rust/noosphere-ns/tests/ns_test.rs

dev: Expose replication/publication/ttl intervals to NameSystemBuilder

---

Cargo.lock
release-please-config.json
rust/noosphere-api/Cargo.toml
rust/noosphere-api/src/client.rs
rust/noosphere-cli/Cargo.toml
rust/noosphere-cli/src/native/commands/auth.rs
rust/noosphere-cli/src/native/commands/serve/authority.rs
rust/noosphere-cli/src/native/commands/serve/route/push.rs
rust/noosphere-collections/Cargo.toml
rust/noosphere-core/Cargo.toml
rust/noosphere-core/src/authority/authorization.rs
rust/noosphere-core/src/authority/verification.rs
rust/noosphere-core/src/data/authority.rs
rust/noosphere-fs/Cargo.toml
rust/noosphere-into/Cargo.toml
rust/noosphere-into/examples/notes-to-html/implementation.rs
rust/noosphere-ns/Cargo.toml
rust/noosphere-ns/src/records.rs
rust/noosphere-storage/Cargo.toml
rust/noosphere/Cargo.toml

BREAKING CHANGE: Several critical dependencies of this library were updated to new versions that contain breaking changes.

chore: Update IPLD-adjacent dependencies

---

rust/noosphere-cli/src/native/commands/serve/ipfs/kubo.rs

Previously, if a Kubo instance was missing a pin, we would get an unexpected response and the client method would return an error result. Now we recover and just mark the block as not pinned (it is acceptable to resend a block that is actually pinned, just a wasteful).

fix: Recover from Kubo pin check

---

rust/noosphere-core/src/data/memo.rs
rust/noosphere/src/ffi/fs.rs
rust/noosphere/src/ffi/key.rs
rust/noosphere/src/ffi/noosphere.rs
rust/noosphere/src/ffi/sphere.rs
swift/Tests/SwiftNoosphereTests/NoosphereTests.swift

This change is a follow-up to #210 where we introduced a new error handling style to the FFI. This change completes the work, changing the rest of our FFI to support the same error handling style.

feat: General error handling in C FFI

---

rust/noosphere-collections/src/hamt/test.rs
rust/noosphere-fs/src/fs.rs
rust/noosphere-storage/src/block.rs
rust/noosphere-storage/src/db.rs
rust/noosphere-storage/src/implementation/tracking.rs
rust/noosphere-storage/src/key_value.rs
rust/noosphere-storage/src/store.rs

This should help us rule out durability issues in our underlying K/V store that may be cropping up when the Subconscious app crashes.

feat: Always flush on SphereFS save

---

.github/workflows/container_images.yaml
images/orb-ns/Dockerfile
images/orb-ns/README.md
images/orb-ns/start.sh

Lots of different ways to handle parameterization here, but a good first pass

dev: initial containerization work for orb-ns

---

rust/README.md
rust/noosphere-into/examples/notes-to-html/implementation.rs
rust/noosphere-into/src/write/native.rs
rust/noosphere/src/sphere/storage.rs

With these changes, all tests passing on Windows

feat: Initial work to get Noosphere building on Windows

---

.github/workflows/run_test_suite.yaml
rust/noosphere/src/sphere/storage.rs

chore: Add windows-latest to test suite.

---

.github/workflows/container_images.yaml
.github/workflows/release.yaml
typescript/package-lock.json

- Fix missing checksum in generated Package.swift
- Fix custom container image tag not being tagged
- Tag "latest" container images on every push to main
- Tag "noosphere-$VERSION" container images on every release

fix: Clean up release workflows

---

.github/workflows/run_test_suite.yaml
c/example/Makefile
c/example/main.c

Add C tests to CI, and fix interpreting uint8 data as char*, as well as a leak.

feat: initial attempt at connecting C tests to CI

---

rust/noosphere-ns/src/dht/node.rs

Was able to reproduce this locally after many tests runs. Was not able to repro locally after this after many test runs. Fixes #311

fix: Intermittent timeouts in DhtNode tests introduced via #308 by adding peers before listening.

---

Cargo.lock
Cargo.toml
rust/noosphere-ns/Cargo.toml
rust/noosphere-ns/src/dht/processor.rs
rust/noosphere-ns/src/dht/swarm.rs

...migrating stub of BannedPeers to the new allow_block_list module.

chore: fix remaining libp2p deprecation issues

---

README.md

docs: Fix roadmap link in README.md

---

rust/noosphere-cli/tests/peer_to_peer.rs
rust/noosphere-sphere/src/context.rs
rust/noosphere-sphere/src/helpers.rs
rust/noosphere-sphere/src/replication.rs

This ties into work @jsantell has been doing to test #320. During play testing today, we got a lead on this bug, so this is a possible fix for the bug.
Fixes #320

fix: Ensure petname link records are replicated

---

rust/noosphere-gateway/src/route/push.rs
rust/noosphere-gateway/src/worker/name_system.rs

feat: re-enable checking of publishable timeframe when publishing link records from the gateway

---

typescript/package-lock.json
typescript/packages/sphere-viewer/package.json

Fixes https://github.com/subconsciousnetwork/noosphere/security/dependabot/21

fix: Update `vite` NPM package for security patch

---

swift/Sources/SwiftNoosphere/Noosphere.swift
swift/Tests/SwiftNoosphereTests/NoosphereTests.swift

Blindly copying the other examples, but it seems to work (both in tests and in Subconscious itself) 😬

feat: Implement nsSphereAuthorityAuthorizationsList Swift FFI wrapper

---

rust/noosphere/src/key/insecure.rs

Fixes #547
```
drwxrwxr-x 2 jsantell jsantell 4096 Aug  3 12:01 .
drwxrwxr-x 3 jsantell jsantell 4096 Jan 17  2023 ..
-rw------- 1 jsantell jsantell  152 Aug  3 12:01 permtest.private
-rw-r--r-- 1 jsantell jsantell   56 Aug  3 12:01 permtest.public
```

feat: store private noosphere keys as owner-readwrite only.

---

rust/noosphere-core/src/data/address.rs
rust/noosphere-gateway/src/worker/name_system.rs
rust/noosphere-sphere/src/context.rs
rust/noosphere-sphere/src/petname/write.rs
rust/noosphere-sphere/src/sync/strategy.rs

feat: Ensure adopted link records are fresher than previous entries

---

.config/nextest.toml
.github/workflows/run_test_suite.yaml

chore: Add slow-timeout to terminate slow running tests in CI. Fixes #706

---

rust/noosphere-common/src/channel.rs
rust/noosphere-core/src/api/v0alpha1/data.rs
rust/noosphere-core/src/api/v0alpha2/data.rs
rust/noosphere-core/src/helpers/context.rs
rust/noosphere-core/src/view/mutation.rs
rust/noosphere-ns/src/bin/orb-ns/runner/config.rs
rust/noosphere/src/ffi/context.rs
rust/noosphere/src/ffi/petname.rs
rust/noosphere/src/platform.rs

* Lints for nightly builds in 2024-03-11, including soundness issue from #863 
* Lints for nightly builds in 2024-03-24

chore: Fix nightly lints for 2024-03-11
