README.md

We are using reference-style links, which should look like `[link][ref]`, not `[link](url)`.
Also:
- Fix a couple URLs that point to repo
- Remove a couple URLs that are no longer used

Fix link syntax in README

---

rust/Cargo.lock
rust/Cargo.toml
rust/noosphere-api/src/authority.rs
rust/noosphere-api/src/client.rs
rust/noosphere-api/src/gateway.rs
rust/noosphere-api/src/lib.rs
rust/noosphere-fs/Cargo.toml
rust/noosphere-fs/src/decoder.rs
rust/noosphere-fs/src/file.rs
rust/noosphere-fs/src/fs.rs
rust/noosphere-fs/src/lib.rs
rust/noosphere-gateway/src/gateway/authority/keeper.rs
rust/noosphere-gateway/src/gateway/commands/serve.rs
rust/noosphere-gateway/src/gateway/handlers/push.rs
rust/noosphere-storage/src/interface.rs
rust/noosphere/src/data/body_chunk.rs
rust/noosphere/src/data/mod.rs
rust/noosphere/src/data/reference.rs

This change introduces an FS-like view over sphere data, in the spirit of APIs we prototyped in the early days of a couple months ago.
Given a sphere identity (a DID string), a block store and a "sphere" store - a store of pointers to our equivalent of "HEAD" for sphere lineages - a user can get a relatively ergonomic API for reading from or writing to slugs in a sphere. The view internally keeps a CID cursor over the lineage of the sphere, and allows the user to ignore most of the details related to IPLD and how history works.
This change is set up to take advantage of the streaming parser feature introduced in subconsciousnetwork/subtext#35, by offering file contents as an `AsyncRead` implementation. This can in turn be passed directly into e.g., the subtext parser, which will return a …

Introduce FS-like view into sphere data

---

rust/Cargo.lock
rust/noosphere-cli/Cargo.toml
rust/noosphere-cli/src/bin/orb.rs
rust/noosphere-cli/src/native/commands/auth.rs
rust/noosphere-cli/src/native/commands/sphere.rs
rust/noosphere-cli/src/native/mod.rs
rust/noosphere-cli/src/native/workspace.rs
rust/noosphere-storage/src/db.rs

This change implements basic support for authorization of other keys with the Noosphere CLI.
- `orb auth add $DID` will generate a UCAN authorization for the given DID and store it in the sphere; you can give it a pet name, or else a random one is generated for you
- `orb auth list [--as-json]` will enumerate the current set of authorizations 
- `orb auth revoke $NAME` will revoke authorization by pet name, removing the authorization from the allowed list and adding a signed revocation of it to the sphere
Fixes #72

Implement `orb auth` subcommand

---

rust/Cargo.lock
rust/noosphere-cli/Cargo.toml
rust/noosphere-cli/src/native/commands/auth.rs
rust/noosphere-cli/src/native/commands/mod.rs
rust/noosphere-cli/src/native/commands/save.rs
rust/noosphere-cli/src/native/commands/status.rs
rust/noosphere-cli/src/native/mod.rs
rust/noosphere-cli/src/native/workspace.rs
rust/noosphere-fs/src/fs.rs
rust/noosphere-into/examples/notes-to-html/implementation.rs
rust/noosphere-into/src/html/into.rs
rust/noosphere-storage/src/db.rs
rust/noosphere-storage/src/memory.rs
rust/noosphere/src/data/headers/content_type.rs
rust/noosphere/src/view/sphere.rs

This change introduces the `orb save` and `orb status` subcommands, as a follow-on to #71 and #80.
The `orb save` command commits content changes in the current workspace to the sphere, signing the revision and displaying the CID of that revision for the user.
The `orb status` command shows you the status of content in the current sphere workspace. It gives you an at-a-glance view of what changes will be performed if `orb save` is invoked.
As a convenience, `orb save` can be filtered using a glob pattern with the `-m` flag.
Files that are saved have their extension stripped. A `content-type` is inferred based on the file extension.
In addition to the implementation of the two new subcommands, some refactoring has been performed on the `SphereFs` construct. Previously, the FS view would …

Implement `orb save` and `orb status` subcommands

---

rust/noosphere-fs/src/fs.rs
rust/noosphere/src/view/mutation.rs

Make `SphereFS::save` return an error when there is neither a non-empty mutation nor any additional headers to save.
Issue: https://github.com/subconsciousnetwork/noosphere/issues/85

SphereFS returns error when saving an empty change (fixes #85)

---

rust/noosphere-api/src/data.rs
rust/noosphere-cli/src/native/commands/config.rs
rust/noosphere-cli/src/native/commands/serve/extractor.rs
rust/noosphere-cli/src/native/commands/sphere.rs
rust/noosphere-fs/src/fs.rs
rust/noosphere-storage/src/db.rs
rust/noosphere/src/data/bundle.rs
rust/noosphere/src/view/sphere.rs

When I tried building and running the tools, I realized there were some warnings output with the runtime / build-time text. Thankfully, these errors made sense™ to me despite my rust-fu being technically non-existent at the moment. So I thought to do something about it.
There were two classes of warnings:
1. Unused imports
1. Unreachable code
I'm pretty confident about the "unused imports" warnings; since this is something my editor can help with. The "unreachable code" bits, I had to trust that the tests already existing in the package would fail if I broke something.
Changelog:
- Implement `orb config` and `orb serve` subcommands (#92)
- Remove unused imports
- Change todo! to // TODO: so Ok(()) is reachable.
_p.s: I'm not responsible for the first point here, but it's part of my …

Clean up build / runtime warnings

---

rust/noosphere-api/Cargo.toml
rust/noosphere-api/README.md
rust/noosphere-cli/Cargo.toml
rust/noosphere-cli/README.md
rust/noosphere-collections/Cargo.toml
rust/noosphere-collections/README.md
rust/noosphere-core/Cargo.toml
rust/noosphere-core/README.md
rust/noosphere-fs/Cargo.toml
rust/noosphere-fs/README.md
rust/noosphere-into/Cargo.toml
rust/noosphere-into/README.md
rust/noosphere-storage/Cargo.toml
rust/noosphere-storage/README.md

Note: the READMEs are just stubs with a high-level description of the crate at this time.

docs: Add crate READMEs and Cargo.toml metadata

---

.github/workflows/run_test_suite.yaml
rust/noosphere-cli/src/native/workspace.rs

The CLI now looks for the nearest ancestor sphere directory when determining what "root" should be used for the purposes of the current action.
Notably, in the recorded video demo for #22 we tried to save from a sub-directory and I got an annoying error. With this change, that will no longer happen.

feat(cli): Find the nearest ancestor sphere

---

.github/workflows/noosphere_apple_build.yaml
.github/workflows/noosphere_cli_build.yaml
.github/workflows/release.yaml
.gitignore
Cargo.lock
Cargo.toml
release-please-config.json
rust/noosphere/.gitignore
rust/noosphere/Cargo.toml
rust/noosphere/README.md
rust/noosphere/examples/generate_header.rs
rust/noosphere/include/module.modulemap
rust/noosphere/src/builder.rs
rust/noosphere/src/error.rs
rust/noosphere/src/ffi.rs
rust/noosphere/src/lib.rs
rust/noosphere/src/platform.rs
rust/noosphere/src/sphere.rs

The `noosphere` crate is the highest level entrypoint into Noosphere APIs that we offer. It re-exports the functionality of most of our other crates, and offers FFI interfaces for C and JS/WASM consumers.
In addition to the `noosphere` crate, this change introduces some major improvements to our Github Actions workflows. Workflows now let you build associated artifacts on demand, and are also assembled into a larger release orchestration.
NOTE: The `noosphere` crate is currently barebones because we just needed to get it to a point where we could compile it for different Apple targets and expose a trivial FFI. The focus of this change is on establishing our automation workflow for these kinds of artifacts.

feat(noosphere): Introduce `noosphere` crate

---

Cargo.lock
rust/noosphere-ns/Cargo.toml
rust/noosphere-ns/src/dht/errors.rs
rust/noosphere-ns/src/dht/mod.rs
rust/noosphere-ns/src/dht/node.rs
rust/noosphere-ns/src/dht/processor.rs
rust/noosphere-ns/src/dht/validator.rs
rust/noosphere-ns/src/lib.rs
rust/noosphere-ns/src/name_system.rs
rust/noosphere-ns/src/records.rs
rust/noosphere-ns/src/validator.rs
rust/noosphere-ns/tests/dht_test.rs
rust/noosphere-ns/tests/ns_test.rs
rust/noosphere-ns/tests/utils/mod.rs

dev: Implement a RecordValidator trait for the NameSystem DHT, and wrap NameSystem validation in the NSRecord::validate function. Fixes #126
Lots of noise here due to adding the `<V: RecordValidator + 'static>` generic, and the async validation bubbling up its asyncness

dev: Implement a RecordValidator

---

rust/noosphere-ns/src/builder.rs
rust/noosphere-ns/src/dht/config.rs
rust/noosphere-ns/src/dht/mod.rs
rust/noosphere-ns/src/dht/node.rs
rust/noosphere-ns/src/dht/processor.rs
rust/noosphere-ns/src/dht/types.rs
rust/noosphere-ns/src/name_system.rs
rust/noosphere-ns/src/records.rs
rust/noosphere-ns/src/utils.rs
rust/noosphere-ns/tests/dht_test.rs
rust/noosphere-ns/tests/ns_test.rs
rust/noosphere-ns/tests/utils/mod.rs

Some cleanups from earlier DHT work, now with a clearer understanding of the system as a whole (and tidying up docs)
* Rename `set_record` terms to `put_record` to align with the underlying DHT methods -- similarly, use `key` instead of `name` for records.
* Use `&[u8]` interfaces for the DHT module
* `#[cfg(doc)]` some modules to cleanup references in docs
* Simplify DHT tests (thanks to above changes) with some util cleanups so we can start to splice together stranger network in tests.

chore: cleanups on some older DHT code and docs

---

design/name-system.md

Initial draft here. Goal here is to define all properties used in the system in order for an independent client to participate in the Noosphere Name System. #124 may change this to be Provider-based, and there's some improvements/clarifications to be made here, but wanted to start discussion.

docs: Initial write up of the Noosphere Name System spec.

---

Cargo.lock
rust/noosphere-ns/Cargo.toml
rust/noosphere-ns/README.md
rust/noosphere-ns/src/bin/bootstrap-nns/cli.rs
rust/noosphere-ns/src/bin/bootstrap-nns/main.rs
rust/noosphere-ns/src/bin/bootstrap-nns/runner/config.rs
rust/noosphere-ns/src/bin/bootstrap-nns/runner/mod.rs
rust/noosphere-ns/src/bin/bootstrap-nns/runner/runner.rs
rust/noosphere-ns/src/bin/bootstrap-nns/utils.rs
rust/noosphere-ns/src/lib.rs
rust/noosphere-ns/src/name_system.rs

dev: First pass on a `bootstrap` CLI in noosphere-ns to spin up DHT bootstrap nodes for the name system.

dev: First pass on a `bootstrap` CLI

---

rust/noosphere-core/src/authority/author.rs
rust/noosphere-core/src/authority/verification.rs
rust/noosphere-core/src/data/address.rs
rust/noosphere-core/src/data/mod.rs
rust/noosphere-core/src/data/sphere.rs
rust/noosphere-core/src/data/strings.rs
rust/noosphere-core/src/view/sphere.rs
rust/noosphere-core/src/view/versioned_map.rs
rust/noosphere-fs/src/fs.rs
rust/noosphere-into/examples/notes-to-html/implementation.rs
rust/noosphere-into/src/html/into.rs
rust/noosphere/src/noosphere.rs
rust/noosphere/src/sphere/builder.rs
rust/noosphere/tests/integration.rs

This is a small-ish change to get our feet in the water with pet names. It introduces a new `VersionedMap` for pet names, where we are mapping a human-readable name to what we call an `AddressIpld`. The address records a DID, and optionally a last known resolved value (which is represented as a JWT).
I also threw in some cleanup: I wrote a declarative macro for enhancing a string-wrapper struct with trait implementations to make the wrappers coherent with strings, and then added string-wrapper structs for JWTs and BIP-39 mnemonics. I also started propagating these structs a bit more.
Fixes #153

Introduce pet names to spheres

---

Cargo.lock
rust/noosphere-cli/Cargo.toml
rust/noosphere-cli/src/native/workspace.rs
rust/noosphere-cli/tests/gateway.rs
rust/noosphere-into/Cargo.toml
rust/noosphere-into/examples/notes-to-html/implementation.rs
rust/noosphere/Cargo.toml
rust/noosphere/src/key/insecure.rs
rust/noosphere/src/platform.rs
rust/noosphere/tests/integration.rs

This is an attempt to clean up the way we create an dispose of temporary directories in the hopes it will help with #167 . Our temporary directory crate was deprecated, it turns out, so we update it here to [`tempfile`](https://crates.io/crates/tempfile). And, we fix a leak that caused temporary directories to go undeleted.
Even if this doesn't fix the flakes in `noosphere`, this is a hygienic improvement :shrug:

chore: Use `tempfile` instead of `temp-dir`

---

typescript/packages/sphere-viewer/src/styles/subtext.ts

Removes CSS that made transclude text smaller than body text. This looks better, in practice.

Make transclude font size same as body font size

---

typescript/README.md
typescript/packages/orb/package.json
typescript/packages/sphere-viewer/package.json

As of this change, `@subconsciousnetwork/orb` has been published to NPM. This was mainly done to test that publishing works as expected, and that the published package can be used with or without a bundler.
Here is a test page on Glitch that loads up the published package via unpkg.com and initializes a `NoosphereContext` (view source and/or console for proof): https://subconscious-sandbox.glitch.me/orb-test.html

feat: Publish `orb` to NPM

---

Cargo.lock
rust/noosphere/Cargo.toml
rust/noosphere/src/ffi/fs.rs
swift/Tests/SwiftNoosphereTests/NoosphereTests.swift

This change introduces two new C FFI functions for dealing with headers, and an example of how to use the API from Swift as a test.

feat: Extend C FFI for header enumeration

---

Cargo.lock
rust/noosphere-ns/Cargo.toml
rust/noosphere-ns/src/dht/node.rs
rust/noosphere-ns/src/dht/processor.rs
rust/noosphere-ns/src/dht/rpc.rs
rust/noosphere-ns/src/dht/swarm.rs
rust/noosphere-ns/tests/dht_test.rs

Bumping libp2p from 0.49.0 to 0.50.0:
* Update to latest APIs.
* Paving way to integrate uplifts https://github.com/libp2p/rust-libp2p/pull/3387
* Reconfigure the `NetworkBehaviour` derive macro. Previously, analyzer would alert warnings and fail (multiple machines) with this macro, but enabling the `macros` feature works like a charm (maybe this was optional before).
* Remove some workarounds in lieu of libp2p features (e.g. we don't have to roll our own Tokio executor anymore)

dev: upgrade libp2p to 0.50.0

---

Cargo.lock
rust/noosphere-core/Cargo.toml
rust/noosphere-core/src/view/sphere.rs
rust/noosphere-core/src/view/versioned_map.rs
rust/noosphere-fs/src/fs.rs
rust/noosphere/Cargo.toml
rust/noosphere/src/ffi/error.rs
rust/noosphere/src/ffi/fs.rs
rust/noosphere/src/ffi/headers.rs
rust/noosphere/src/ffi/mod.rs
rust/noosphere/src/ffi/noosphere.rs
rust/noosphere/src/ffi/sphere.rs
swift/Tests/SwiftNoosphereTests/NoosphereTests.swift

This change implements a few additional pieces of C FFI:
- Sync a sphere with a configured gateway
- Remove (unlink) a slug from the content space
- Get all changed slugs since some version of the sphere
- Get all links in the current version of the sphere
- Get the current CID version of a sphere
- Get the CID version of a file
Additionally, this change introduces an experimental error handling style for C FFI. An optional uninitialized error pointer can be provided as an "out" parameter, which is conventionally the last parameter of any function that supports this style. On the Rust side of the FFI, we have a helper trait that enables us to lazily initialize the pointer under an error condition while preserving memory safety and enabling use of syntax niceties like `?`.
Fixes #204
Fixes …

feat: Sphere sync and change diff in C FFI

---

rust/noosphere-core/Cargo.toml
rust/noosphere-core/src/view/sphere.rs
rust/noosphere-core/src/view/timeline.rs
rust/noosphere-fs/src/fs.rs
swift/Tests/SwiftNoosphereTests/NoosphereTests.swift

This was causing one too many "changes" to be reported by the corresponding sphere APIs.

fix: Ensure that sphere changes exclude `since`

---

Cargo.lock
rust/noosphere-ns/Cargo.toml
rust/noosphere-ns/src/bin/orb-ns/cli.rs
rust/noosphere-ns/src/bin/orb-ns/cli_address.rs
rust/noosphere-ns/src/bin/orb-ns/main.rs
rust/noosphere-ns/src/bin/orb-ns/runner/config.rs
rust/noosphere-ns/src/bin/orb-ns/runner/mod.rs
rust/noosphere-ns/src/bin/orb-ns/utils.rs
rust/noosphere-ns/src/client.rs
rust/noosphere-ns/src/dht/node.rs
rust/noosphere-ns/src/dht/processor.rs
rust/noosphere-ns/src/name_system.rs
rust/noosphere-ns/src/records.rs
rust/noosphere-ns/src/server/client.rs
rust/noosphere-ns/src/server/server.rs

* Implements `orb-ns status`
* Implements `orb-ns records [(get $DID)|(put $RECORD)]`
* Implements `orb-ns peers [ls|(add $ADDR)]`
* Synchronizes orb-ns flags with the config file variant for bootstrap nodes
* Allow SocketAddr/Url/Multiaddr to be represented by SocketAddr/IpAddr/u16 Ports in orb-ns flags and configs.

feat: Initial integration of orb-ns CLI into the Name System's operator API

---

rust/noosphere/src/platform.rs

We were not exporting this load-bearing test helper in the Apple conditional compilation case (incidentally, highlighting that we don't run the Rust test suite on Apple hardware).
Fixes #226

chore: Make tests run on Apple hardware

---

.github/workflows/container_images.yaml
images/orb/Dockerfile
images/orb/start.sh

This change is small but several weeks in the making. It implements a Github workflow for building and pushing containers to a private registry on GCP, from which we may deploy them as part of a managed service for the benefit of our users.
Containers are automatically built and pushed for each PR, and are available via the tag `pr-$PR_NUMBER`. The same workflow may be dispatched (manually or via a caller workflow) to build and push containers against arbitrary tag names. So, eventually we can integrate this with our release workflow.

chore: Minimum viable container builds

---

rust/noosphere-cli/src/native/commands/auth.rs
rust/noosphere-core/src/view/sphere.rs
rust/noosphere-ns/src/records.rs
rust/noosphere-ns/tests/ns_test.rs

In some scenarios, both authorization and delegated tokens set their expiration time to be (NOW + 10000 years). If the delegated and auth tokens aren't created within the same timestamp-second, then the delegated token's lifetime exceeds its attenuation. This occurs intermittently (Fixes #248).

fix: Limit delegated UCAN's lifetime to authorization token's lifetime where appropriate

---

c/.gitignore
c/README.md
c/example/Makefile
c/example/main.c
rust/noosphere/examples/generate_header.rs
rust/noosphere/src/ffi/header_transformer.rs
rust/noosphere/src/ffi/mod.rs

Need to figure out some text encoding stuff and clean ups, but this C snippet links and runs against libnoosphere

feat: Initial example of C integration

---

rust/noosphere/src/ffi/header_transformer.rs

Use an ordered BTreeMap to replace class token keys so that class names that are subsets of other class names are replaced appropriately.

fix: FFI header generation

---

.github/workflows/container_images.yaml
.github/workflows/run_test_suite.yaml
rust/noosphere-sphere/src/content/mod.rs
rust/noosphere-sphere/src/lib.rs
rust/noosphere-sphere/src/walker.rs
rust/noosphere/src/ffi/fs.rs
rust/noosphere/src/ffi/key.rs
rust/noosphere/src/ffi/noosphere.rs
rust/noosphere/src/ffi/petname.rs
rust/noosphere/src/ffi/sphere.rs
rust/noosphere/src/wasm/fs.rs
swift/Tests/SwiftNoosphereTests/NoosphereTests.swift

This is a follow-up to #253 that implements that C FFI surface for petname support. As part of a general transition away from the deprecated `SphereFs` and towards `SphereContext` + traits, this also tweaks the signatures of FFI methods in a (hopefully) non-breaking way to indicate that `SphereFs` is no longer a thing.
Note that this change does not include validation of petname records. A change is already in-progress to implement validation in the gateway.
Fixes #243

feat!: Implement C FFI for petname management

---

Cargo.lock
rust/noosphere-cli/src/native/workspace.rs
rust/noosphere-cli/tests/gateway.rs
rust/noosphere-core/src/data/address.rs
rust/noosphere-core/src/data/bundle.rs
rust/noosphere-core/src/data/links.rs
rust/noosphere-core/src/data/memo.rs
rust/noosphere-core/src/tracing.rs
rust/noosphere-core/src/view/mutation.rs
rust/noosphere-core/src/view/sphere.rs
rust/noosphere-core/src/view/timeline.rs
rust/noosphere-core/src/view/versioned_map.rs
rust/noosphere-gateway/src/gateway.rs
rust/noosphere-gateway/src/ipfs.rs
rust/noosphere-gateway/src/nns.rs
rust/noosphere-gateway/src/route/fetch.rs
rust/noosphere-gateway/src/route/identify.rs
rust/noosphere-gateway/src/route/push.rs
rust/noosphere-into/Cargo.toml
rust/noosphere-into/src/into/html/sphere.rs
rust/noosphere-into/src/transform/sphere/html.rs
rust/noosphere-sphere/src/content/read.rs
rust/noosphere-sphere/src/content/write.rs
rust/noosphere-sphere/src/cursor.rs
rust/noosphere-sphere/src/internal.rs
rust/noosphere-sphere/src/petname/read.rs
rust/noosphere-sphere/src/petname/write.rs
rust/noosphere-sphere/src/sync/gateway.rs
rust/noosphere-sphere/src/sync/mod.rs
rust/noosphere-sphere/src/walker.rs

This change is a precursor to #269 . It represents two important revisions that clean things up to prepare for sphere traversal.
1. The gateway is now generic to the storage type and sphere context provider it supports
2. Sphere link values are now `MemoIpld` instead of `Cid`
(1) enables us to pass in an `IpfsStorage`-wrapped storage to the gateway without changing the underlying implementation to be aware of it.
(2) aligns links with the way we store other constructs (like petnames and authorizations), and enables us to clean up a gross corner of how we determine what must be bundled for a given sphere revision to be transferred over the network.

feat: Revise links and gateway

---

rust/noosphere-cli/Cargo.toml
rust/noosphere-cli/src/native/commands/auth.rs
rust/noosphere-cli/src/native/commands/config.rs
rust/noosphere-cli/src/native/commands/save.rs
rust/noosphere-cli/src/native/commands/serve.rs
rust/noosphere-cli/src/native/commands/sphere.rs
rust/noosphere-cli/src/native/commands/status.rs
rust/noosphere-cli/src/native/commands/sync.rs
rust/noosphere-cli/src/native/mod.rs
rust/noosphere-cli/src/native/workspace.rs

...and other orb papercuts.
* Prevents ambitious creation of an uninitialized ".sphere" dir that lacks a "user_key_name", fixing #232. (thus causing many phantom `.sphere` dirs)
* Updates and constrains "clap" to match "noosphere-ns".
* Adds a hidden alias of "ls" to "list" in "orb" e.g. "orb key ls".
* Hoists tracing utility to native::main

feat: Improve "orb" error messaging when sphere directory is expected and does not exist

---

c/example/main.c
rust/noosphere-gateway/src/worker/syndication.rs
rust/noosphere/src/ffi/context.rs
rust/noosphere/src/ffi/mod.rs
swift/Tests/SwiftNoosphereTests/NoosphereTests.swift

This change introduces a C FFI for sphere traversal.
This change also breaks a bunch of existing FFI by renaming functions to better align with the `SphereContext` refactor we did in #253. Only the names of functions have been changed. The semantics remain the same.
Additionally, the change fixes the C example, which has actually been broken for a little while.
I really wanted to include an integration test for this one, but it's actually a lot harder to do than it seems. We need to spin up two gateways and a name system node as separate processes in order to perform the test. This means that we would have to build both `orb` and `orb-ns` for the MacOS target before running the Swift tests and then write some helper code to spin them up during a test. In the end, we already cover the …

feat!: Sphere traversal C FFI

---

docs/api/build_c.sh
docs/api/doxyfile
docs/api/doxygen_index.md
rust/noosphere-core/src/data/strings.rs
rust/noosphere-core/src/view/mutation.rs
rust/noosphere-into/src/transcluder/content.rs
rust/noosphere-sphere/src/context.rs
rust/noosphere-storage/src/block.rs
rust/noosphere/src/ffi/context.rs
rust/noosphere/src/ffi/error.rs
rust/noosphere/src/ffi/headers.rs
rust/noosphere/src/ffi/noosphere.rs
rust/noosphere/src/ffi/petname.rs
rust/noosphere/src/ffi/sphere.rs
rust/noosphere/src/key/insecure.rs

* Expand @\class and @\memberof Doxygen relationships amongst FFI functions.
* Refine some FFI docs for consistent language and adapted to Doxygen's "summary" and "detailed" views (via newlines).
* Fix up rustdoc lints.

chore: additional work on FFI documentation.

---

rust/noosphere-gateway/src/again.rs
rust/noosphere-gateway/src/lib.rs
rust/noosphere-gateway/src/try_or_reset.rs
rust/noosphere-gateway/src/worker/name_system.rs
rust/noosphere-ipfs/src/client/kubo.rs

This introduces an `TryOrReset` construct that makes initialization of HTTP clients more resilient. In the case of both the name system and gateway APIs, client initialization is predicated on verifying the identity of the node we are talking to. `TryOrReset` enables us to express usage of a client that is resilient to failures related to identifying nodes, while mostly retaining the efficiency of the current pattern where client initialization only has to happen once.

fix: Introduce `TryOrReset` to help worker threads

---

Cargo.lock
rust/noosphere-ipfs/Cargo.toml
rust/noosphere-ipfs/src/client/kubo.rs
rust/noosphere-ipfs/src/lib.rs
rust/noosphere-ipfs/src/storage.rs

* IpfsStore::get_block now resolves blocks with the correct output-codec.
* IPFS tests (--features test_kubo) could produce false positives by relying on previously cached values in the IPFS instance. Test data now is randomized.
* Add real test against IPFS for a non-existant block via BlockStoreRetry and IpfsStore

Several updates for noosphere-ipfs

---

rust/noosphere-ipfs/src/client/kubo.rs
rust/noosphere-ipfs/src/lib.rs
rust/noosphere-ipfs/src/storage.rs
rust/noosphere-ns/src/dht/processor.rs
rust/noosphere-ns/src/name_system.rs
rust/noosphere-ns/src/records.rs

* Adds tracing to relevant DHT commands, IPFS lookups, and record validations. Future improvements could include spans that follow DHT operations logically (responses from the DHT are polled and reconciled with one or many top-level requests), and better formatting of Cids/Records.
* Remove some redundant, ill-formatted tracing

feat: Add additional tracing instrumentation to noosphere-ns and noosphere-ipfs

---

.vscode/settings.json
Cargo.lock
Cargo.toml
rust/noosphere-core/src/authority/author.rs
rust/noosphere-core/src/authority/authorization.rs
rust/noosphere-into/src/into/html/sphere.rs
rust/noosphere-ipfs/src/client/gateway.rs
rust/noosphere-ipfs/src/client/kubo.rs
rust/noosphere-ipfs/src/client/mod.rs
rust/noosphere-ipfs/src/storage.rs
rust/noosphere-sphere/src/context.rs
rust/noosphere-sphere/src/cursor.rs
rust/noosphere-sphere/src/helpers.rs
rust/noosphere-sphere/src/lib.rs
rust/noosphere-sphere/src/replication.rs
rust/noosphere-sphere/src/walker.rs
rust/noosphere-storage/src/db.rs
rust/noosphere-storage/src/implementation/memory.rs
rust/noosphere-storage/src/implementation/native.rs
rust/noosphere-storage/src/implementation/tracking.rs
rust/noosphere-storage/src/implementation/web.rs
rust/noosphere-storage/src/storage.rs
rust/noosphere/Cargo.toml
rust/noosphere/src/ffi/context.rs

This change implements recursive petname traversal. Most of the change is a test that was really annoying to write :sweat_smile: 
Fixes #305

feat: Recursive petname traversal

---

.vscode/settings.json
Cargo.lock
Cargo.toml
rust/noosphere-cli/tests/peer_to_peer.rs
rust/noosphere-sphere/src/context.rs
rust/noosphere/src/ffi/context.rs
swift/Tests/SwiftNoosphereTests/NoosphereTests.swift

This change makes double-darn sure that we aren't panicking unexpectedly when dealing with slashlinks in the FFI. It also changes some of the error semantics of traversal. Previously, trying to traverse to a petname that isn't assigned to a DID would result in an error. Now, it results in a `None` (similar to how reading a slug that isn't assigned results in `None`).

fix: Unreachable petname sequence is not an error

---

rust/noosphere/src/ffi/context.rs
swift/Tests/SwiftNoosphereTests/NoosphereTests.swift

Context:
>  Right now when I call `ns_sphere_traverse_by_petname` I get back a pointer to a `ns_sphere_t` which we wrap in our own `Sphere` Swift type. That is all good except that `Sphere` needs to know the DID of the `ns_sphere_t` it holds, but (afaict?) there is no easy way for me to get it reliably when traversing to a fully qualified petname (e.g. `@ben.chris.jordan`).
> I find myself wishing for either:
> 1. `ns_sphere_identity_get` so I can read the DID out of the sphere post-traversal
> 2. `ns_resolve_did` which can translate from a fully qualified petname to a DID (resolve is overloaded as a term)
> Leaning towards (1). I can work around this by traversing one hop at a time in a loop and retrieving each DID along the way using `ns_sphere_petname_get` but it seems a shame when …

Introduce `ns_sphere_identity` FFI call

---

Cargo.lock
Cargo.toml
rust/noosphere-core/src/view/mutation.rs
rust/noosphere-sphere/src/context.rs
rust/noosphere/Cargo.toml
rust/noosphere/src/ffi/context.rs
rust/noosphere/src/ffi/petname.rs
rust/noosphere/src/ffi/sphere.rs
rust/noosphere/src/noosphere.rs
rust/noosphere/src/platform.rs
rust/noosphere/src/sphere/channel.rs
rust/noosphere/src/sphere/mod.rs
rust/noosphere/src/wasm/noosphere.rs
rust/noosphere/src/wasm/sphere.rs
rust/noosphere/tests/integration.rs

This change introduces a `SphereChannel`, which enables us to execute read-only and read-write streams of work on spheres concurrently or in parallel. Standard race condition considerations apply: if you intersperse reads and parallel writes, the values that are read will be subject to race results (for example).
Although the mutable and immutable sides of the channel do not block each other, it's still possible for immutable reads to reach out to the network (which means any given immutable read may take a beat to finish, subject to network conditions).

feat: Sphere writes do not block immutable reads

---

Cargo.lock
rust/noosphere-ns/Cargo.toml
rust/noosphere-ns/src/dht/node.rs
rust/noosphere-ns/src/dht/processor.rs
rust/noosphere-ns/src/dht/swarm.rs
rust/noosphere-ns/src/name_system.rs

* Consistently use `libp2p::identity::Keypair` rather than `libp2p::core::identity::Keypair` and use the `libp2p-identity` crate recently introduced. Rework some of the decoding methods.
* New keys use secret key only for de/encoding -- the `ed25519_to_bytes` helper could be configured to use this, or removed completely if inlined into the `NameSystemKeyMaterial` trait.
* Remove deprecated/unused mplex module
* Replace `Swarm::with_tokio_executor`
* New `libp2p_allow_block_list` module requires more configuring with our mixed `DhtBehavior` (implementing for both kad/identify underlying behaviors), so `SwarmEvent::BannedPeer` event remains deprecated

chore: Fix deprecation notices from libp2p 0.51.3

---

rust/noosphere-gateway/src/worker/name_system.rs
rust/noosphere-ns/src/bin/orb-ns/cli/processor.rs
rust/noosphere-ns/src/bin/orb-ns/runner/runner.rs
rust/noosphere-ns/src/builder.rs
rust/noosphere-ns/src/dht/node.rs
rust/noosphere-ns/src/dht/processor.rs
rust/noosphere-ns/src/dht/rpc.rs
rust/noosphere-ns/src/dht_client.rs
rust/noosphere-ns/src/helpers.rs
rust/noosphere-ns/src/lib.rs
rust/noosphere-ns/src/name_resolver.rs
rust/noosphere-ns/src/name_system.rs
rust/noosphere-ns/src/records.rs
rust/noosphere-ns/src/server/client.rs
rust/noosphere-ns/src/server/handlers.rs
rust/noosphere-ns/src/server/server.rs
rust/noosphere-ns/src/utils.rs
rust/noosphere-ns/tests/ns_test.rs

* Decouple validity vs expiration in NsRecord::validate.
* Fixes #264, using response from name system server.
* Remove "local cache" from NameSystem, as its a bit dated and redundant with libp2p Kademlia storage, where persistence and validity should be handled.
* Rename s/NameSystemClient/DhtClient and separate p2p nature from the name resolver, via NameResolver trait (publish, resolve) for consumer usage (e.g. hiding those quorum rules from gateway).

feat: Enable support of quorum=0 for DHT during infra bootstrapping phase

---

Cargo.lock
rust/noosphere-ns/src/dht/swarm.rs

One of the sub-libp2p packages (libp2p_noise) has updated. Not sure why I'm getting these notices without explicitly having updated the subpackage (which was done in order to reconcile the warnings in the first place, in order to have the suggestions available), similar to the previous deprecation warning fix by resetting the dependencies.

chore: Fix deprecation notes for updated libp2p_noise crate, update dependencies

---

Cargo.lock
Cargo.toml
rust/noosphere-core/Cargo.toml

The typo in the dependency was preventing us from publishing to crates.io.
And, the dependency is not used (which is why we didn't see any errors in CI). So, we remove it.

fix: Remove vestigial `tracing-core` dependency

---

.github/workflows/noosphere_apple_build.yaml
.github/workflows/noosphere_cli_build.yaml
.github/workflows/release.yaml
.github/workflows/run_test_suite.yaml

`actions/checkout` updated to v3; the actions-rs actions (cargo, toolchain) seem no longer maintained for a long time. There are a handful of potential forks, but the functionality is inlineable.
[ibnesayeed/setup-ipfs@master](https://github.com/ibnesayeed/setup-ipfs) is still on node12 (https://github.com/ibnesayeed/setup-ipfs/issues/178, https://github.com/ibnesayeed/setup-ipfs/issues/162), the last of our warnings.

chore: Fix deprecation Github actions

---

Cargo.lock
Cargo.toml
rust/noosphere-api/src/data.rs
rust/noosphere-core/src/authority/author.rs
rust/noosphere-core/src/authority/verification.rs
rust/noosphere-core/src/view/sphere.rs
rust/noosphere-gateway/src/authority.rs
rust/noosphere-ns/src/records.rs
rust/noosphere-ns/tests/ns_test.rs

Thanks to @cdata and https://github.com/ucan-wg/rs-ucan/pull/83, we can construct a ProofChain with a valid, yet expired, record. Add a test, and change the behavior of other tests: this is now allowed!

feat: Enable expired yet valid records in the name system. Update to ucan 0.2.0

---

Cargo.lock
images/orb-ns/start.sh
images/orb/start.sh
rust/noosphere-cli/tests/peer_to_peer.rs
rust/noosphere-core/src/tracing.rs
rust/noosphere-gateway/src/worker/name_system.rs
rust/noosphere-ns/Cargo.toml
rust/noosphere-ns/src/bin/orb-ns/runner/config.rs
rust/noosphere-ns/src/bin/orb-ns/runner/runner_implementation.rs
rust/noosphere-ns/src/dht/config.rs
rust/noosphere-ns/src/records.rs
rust/noosphere-ns/src/server/client.rs
rust/noosphere-ns/src/server/handlers.rs
rust/noosphere-ns/src/server/implementation.rs
rust/noosphere-ns/tests/ns_test.rs

* remove mutex from NameSystem's APIServer
* Add logs for RUST_LOG, NOOSPHERE_LOG in image startup scripts
* add `orb` and `orb_ns` in default tracing
Added here, but not immediate relevant:
* support defining partial DhtConfig values via TOML: ultimately we want to expose these knobs, but turns out libp2p's `query_timeout` is not the overall request timeout that we want currently (as a "request" is comprised of several "queries")
* improve `NsRecord`'s Debug formatting: useful, but really need to fix the debug representation of libp2p's `Record`
* remove `tracing_subscriber` from noosphere_ns, causing wild logging results (unfortunately did not fix tracing weirdness in noosphere_ns)

Update orb-ns for cluster

---

.github/workflows/release.yaml

During the latest release (last week), we hit a really lame bug in `release-please`: https://github.com/googleapis/release-please/issues/1896
TL;DR, `release-please` doesn't currently detect that a Cargo workspace member has changed, if that member uses [workspace dependency inheritance](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table) and also one of its inherited dependencies changed at the workspace level.
This bug led to a bad release where `noosphere-storage` technically should have had a release due to a version change in an inherited dependency. Since it didn't have a release, it is now incompatible with all the other crates that did get released.
This PR switches us to use a patched version of `release-please` that supports detecting changes in …

fix: Cargo workspace inheritance in `release-please`

---

.github/workflows/release.yaml

This change adds a step to our release that commits and tags `Package.swift` so that it points to the latest Noosphere release. The latest Noosphere release is tagged as `noosphere-$VERSION`, and the corresponding SwiftNoosphere release is tagged as `swift-noosphere-$VERSION`.
Fixes #135

chore: Commit and tag Package.swift during release

---

rust/noosphere-sphere/src/cursor.rs
rust/noosphere-sphere/src/has.rs
rust/noosphere-sphere/src/petname/read.rs
rust/noosphere-sphere/src/walker.rs
rust/noosphere/src/ffi/petname.rs
swift/Sources/SwiftNoosphere/Noosphere.swift
swift/Tests/SwiftNoosphereTests/NoosphereTests.swift

This introduces a built-in facility for getting all of the petnames assigned to a DID at a given version of a sphere. The discovery is limited to petnames and DIDs that are in the current sphere's address book.
Since petnames are encoded `petname -> DID` in the data structure, we compute the inverse assignments on-demand and cache the results for a given version of the sphere. This represents a basic optimization over an expensive operation. In time, we may be able to optimize by only computing updates based on sphere history deltas (https://github.com/subconsciousnetwork/noosphere/issues/383).
Also included in this change is the corresponding callback-based C FFI, and a Swift helper and example test.
Fixes #358

feat: Get petnames assigned to a DID for a sphere

---

rust/noosphere-gateway/src/route/push.rs
rust/noosphere-gateway/src/worker/name_system.rs
rust/noosphere-gateway/src/worker/syndication.rs
rust/noosphere-ns/src/helpers.rs

Enables gateways to validate a records' proof chain before adoption over IPFS, and verify expiry before publishing. Fixes #257. Changes in `syndication.rs` are exclusively from moving the logic inside a function to catch errors without taking down the processor (only logic change is early aborting if IPFS node isn't found).

feat: validate link records on the gateway

---

rust/noosphere/src/ffi/petname.rs
swift/Tests/SwiftNoosphereTests/NoosphereTests.swift

feat: return `None` instead of throwing in `ns_sphere_petname_resolve()` when a petname cannot be resolved.

---

Cargo.lock
Cargo.toml
rust/noosphere-api/Cargo.toml
rust/noosphere-car/Cargo.toml
rust/noosphere-cli/Cargo.toml
rust/noosphere-cli/tests/peer_to_peer.rs
rust/noosphere-collections/Cargo.toml
rust/noosphere-core/Cargo.toml
rust/noosphere-gateway/Cargo.toml
rust/noosphere-into/Cargo.toml
rust/noosphere-ipfs/Cargo.toml
rust/noosphere-ns/Cargo.toml
rust/noosphere-ns/src/bin/orb-ns/cli/mod.rs
rust/noosphere-ns/src/bin/orb-ns/runner/config.rs
rust/noosphere-sphere/Cargo.toml
rust/noosphere-storage/Cargo.toml
rust/noosphere/Cargo.toml

Cleaning up some dependencies...
* Update hyper to latest 0.14.26 (fixes https://github.com/subconsciousnetwork/noosphere/security/dependabot/7, https://github.com/subconsciousnetwork/noosphere/security/dependabot/3, https://github.com/subconsciousnetwork/noosphere/security/dependabot/4)
* Replace (deprecated) `tempdir` from noosphere_ns with `tempfile`, in line with other noosphere crates, and promote to workspace crate. Remove vestigial usage of `tempfile` in noosphere_gateway. Fixes `tempdir`s transitive dependency of `remove_dir_all` https://github.com/subconsciousnetwork/noosphere/security/dependabot/15.
* Remove unused dependencies (via `cargo-udeps`):
* `multipart` in several noosphere crates (removes several `iron` and older `hyper` versions)
* Many others, including our own …

chore: Remove unused dependencies, and update/replace dependencies with security advisories

---

rust/noosphere-cli/tests/peer_to_peer.rs
rust/noosphere-core/src/data/address.rs
rust/noosphere-gateway/src/route/push.rs
rust/noosphere-gateway/src/worker/name_system.rs
rust/noosphere-ns/src/bin/orb-ns/cli/mod.rs
rust/noosphere-ns/src/dht_client.rs
rust/noosphere-ns/src/helpers.rs
rust/noosphere-ns/src/name_system.rs
rust/noosphere-sphere/src/content/write.rs
rust/noosphere-sphere/src/context.rs
rust/noosphere-sphere/src/cursor.rs
rust/noosphere-sphere/src/helpers.rs
rust/noosphere-sphere/src/petname/write.rs
rust/noosphere-sphere/src/replication/stream.rs
rust/noosphere-sphere/src/sync/strategy.rs

After investigating https://github.com/subconsciousnetwork/subconscious/issues/608, a few issues were uncovered related to how petnames are resolved in the gateway. Most importantly, the gateway was suffering from the effects of a race condition when adopting petnames. But, addressing this uncovered a more subtle problem: it is not safe for us to blindly adopt link records that don't match up with the petname we are adopting them against. For example, consider the following sequence of events:
1. A petname is assigned to a DID
2. During sync, the gateway kicks off a parallel job to resolve the petname
3. Meanwhile, we unassign the petname
4. We sync, the gateway takes no action (no new names to resolve)
5. Then, the original resolve job finishes and comes back with a record
Prior to this …

fix: Resolve petnames in correct order

---

.github/dependabot.yml

This change checks in a config that should enable Dependabot to open PRs to update package versions for both Cargo and NPM packages.

Enable Dependabot package updates

---

Cargo.lock
Cargo.toml
rust/noosphere-core/Cargo.toml
rust/noosphere-core/src/tracing.rs

This rolls back part of #437 . The result of Sentry initialization has to outlive the inner lifetime of whatever process it's observing, so it's better to conceptualize it as initialized outside of the `initialize_tracing` helper. Meanwhile, `sentry_tracing::layer()` can just exist as part of the subscriber with or without an initialized Sentry.
Also, uplifted the `sentry-tracing` dep to the workspace level.

chore: Remove ineffective Sentry initialization

---

rust/noosphere-cli/README.md

chore: Documentation on how the CLI works

---

Cargo.lock
Cargo.toml
c/example/main.c
rust/noosphere-api/src/client.rs
rust/noosphere-api/src/data.rs
rust/noosphere-cli/src/native/commands/auth.rs
rust/noosphere-core/Cargo.toml
rust/noosphere-core/src/authority/author.rs
rust/noosphere-core/src/authority/capability.rs
rust/noosphere-core/src/data/address.rs
rust/noosphere-core/src/data/sphere.rs
rust/noosphere-core/src/view/mutation.rs
rust/noosphere-core/src/view/sphere.rs
rust/noosphere-gateway/src/authority.rs
rust/noosphere-gateway/src/route/fetch.rs
rust/noosphere-gateway/src/route/identify.rs
rust/noosphere-gateway/src/route/push.rs
rust/noosphere-gateway/src/route/replicate.rs
rust/noosphere-gateway/src/worker/name_system.rs
rust/noosphere-ns/src/bin/orb-ns/cli/mod.rs
rust/noosphere-ns/src/dht_client.rs
rust/noosphere-ns/src/name_resolver.rs
rust/noosphere-ns/tests/ns_test.rs
rust/noosphere-sphere/src/context.rs
rust/noosphere-sphere/src/helpers.rs
rust/noosphere-sphere/src/sync/strategy.rs

Building off of https://github.com/ucan-wg/rs-ucan/pull/105, temporarily targeting the GitHub branch.
Changes:
* Provide `None` hasher to `witnessed_by`
* Expiration can now be empty, handle
* Use `generate_capability()` where appropriate
* Facts are now always maps, key the link value under `LINK_RECORD_FACT_NAME` as `"link"` -- open to suggestions here, probably should be less generic than "link", though not completely noosphere-specific as these could be shared outside the nooverse
Rename: 
* `Capability` => `CapabilityView`
* `With` => `Resource`
* `Action` => `Ability`
* `Resource` => `ResourceUri`
* `SphereAction` => `SphereAbility`

feat: Update to rs-ucan 0.4.0, implementing Ucan 0.10ish.

---

Cargo.lock
Cargo.toml
rust/noosphere-api/Cargo.toml
rust/noosphere-api/src/client.rs
rust/noosphere-car/README.md
rust/noosphere-car/src/lib.rs
rust/noosphere-cli/Cargo.toml
rust/noosphere-gateway/Cargo.toml
rust/noosphere-gateway/src/worker/syndication.rs
rust/noosphere-ipfs/Cargo.toml
rust/noosphere-ipfs/src/client/kubo.rs
rust/noosphere-sphere/Cargo.toml
rust/noosphere-sphere/src/replication/car.rs
rust/noosphere-sphere/src/replication/stream.rs

Fixes #446
TBD what we have to do to mark noosphere-car as deprecated -- will need to remove the code and workspace/release-it entries

chore: Replace noosphere-car with iroh-car throughout the noosphere crates.

---

.github/workflows/noosphere_apple_build.yaml
c/example/Makefile
scripts/build-framework.sh
scripts/generate-headers.sh
scripts/swift-test.sh

Provide a script to generate headers that uses codegen_units=1 when building on macos to circumvent a header generation issue. Update CI and C makefile to use this script. Fixes #473.
Also fixes a linker issue on macos for the C example. Fixes #476.

chore: fix header generation on macos

---

.github/workflows/run_test_suite.yaml

Our workflow script for getting `chromedriver` for our browser-targeted tests broke from under us due to changes in the Chromium project's release processes (see: https://groups.google.com/g/chromedriver-users/c/clpipqvOGjE).
We originally cribbed the script from https://github.com/SeleniumHQ/selenium/blob/5d108f9a679634af0bbc387e7e3811bc1565912b/.github/actions/setup-chrome/action.yml
However, Selenium has moved to using https://github.com/browser-actions/setup-chrome which does not handle setting up `chromedriver`.
The original mechanism we depended on to discover the correct `chromedriver` version has been replaced by the static JSON published in https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints
So, this change adapts our workflow scripts to use the new …

fix: Get `chromedriver` from a new location

---

.github/workflows/container_images.yaml

This fix was already implemented in https://github.com/subconsciousnetwork/noosphere/commit/29472323c8ff5797ac7d3713fb1109e2235f6505 but was accidentally reverted in https://github.com/subconsciousnetwork/noosphere/commit/4940c331ed6fa0295b3ed93ec2f39133b3f973d2

fix: Disallow Dependabot from building containers again

---

Cargo.lock
rust/noosphere-api/src/data.rs
rust/noosphere-core/Cargo.toml
rust/noosphere-core/src/error.rs
rust/noosphere-core/src/lib.rs
rust/noosphere-core/src/view/sphere.rs
rust/noosphere-sphere/src/authority/read.rs
rust/noosphere/src/ffi/authority.rs
rust/noosphere/src/ffi/context.rs
rust/noosphere/src/ffi/error.rs
rust/noosphere/src/ffi/petname.rs
rust/noosphere/src/ffi/sphere.rs
rust/noosphere/src/lib.rs
swift/Sources/SwiftNoosphere/Noosphere.swift
swift/Tests/SwiftNoosphereTests/NoosphereTests.swift

This adds C FFI support for verifying that an authorization is still valid, given its CID. The bulk of the implementation here has already shipped, we just didn't have an FFI wrapper for it.

feat: C FFI to verify authorizations

---

swift/README.md

chore: update swift documentation that the build script works on aarch64

---

Cargo.lock
Cargo.toml
rust/noosphere-car/Cargo.toml
rust/noosphere-car/src/header.rs
rust/noosphere-car/src/reader.rs
rust/noosphere-collections/Cargo.toml

Updating `multihash` causes conflicts with `cid`, as `cid` re-exports its own `multihash` and `multibase`.

chore: Remove multihash as a dependency and rely on the exports from the cid crate.

---

rust/noosphere-storage/src/implementation/native.rs

.. rather than using sled::Tree::flush_async, which can cause deadlocks. Fixes #403

feat: Synchronously flush sled DB

---

release-please-config.json
rust/noosphere-car/src/header.rs
rust/noosphere-car/src/lib.rs
rust/noosphere-car/src/reader.rs
rust/noosphere-car/src/writer.rs
rust/noosphere-car/tests/car_file_test.rs

* Structs needed to be marked as deprecated in order to float the deprecation to the docs landing page (the export was insufficient)
* Should be sure that the release process doesn't increment or change the version on publish (though if it bumps to `0.3.1+deprecated`, oh well)
* FWIW `0.3.0` < `0.3.0+deprecated`

chore: mark noosphere-car's version as 0.3.0+deprecated

---

Cargo.lock
rust/noosphere-cli/src/native/commands/sphere/history.rs
rust/noosphere-cli/src/native/render/writer.rs
rust/noosphere-cli/tests/cli.rs
rust/noosphere-ipfs/Cargo.toml
rust/noosphere-ipfs/src/client/kubo.rs

This fixes a bug that I encountered when adding-then-removing a note in Subconscious, and later syncing via `orb`. `orb` would attempt to look up the rendered file path for a file that was never rendered (because of how we buffer/flatten the effect multiple new versions of history), and then abort because it couldn't find an expected path.

fix: Better handling of removed content in `orb`

---

Cargo.lock
Cargo.toml
rust/noosphere-api/Cargo.toml
rust/noosphere-cli/Cargo.toml
rust/noosphere-collections/Cargo.toml
rust/noosphere-collections/src/hamt/hamt_implementation.rs
rust/noosphere-core/Cargo.toml
rust/noosphere-gateway/Cargo.toml
rust/noosphere-into/Cargo.toml
rust/noosphere-ipfs/Cargo.toml
rust/noosphere-ns/Cargo.toml
rust/noosphere-sphere/Cargo.toml
rust/noosphere-storage/Cargo.toml
rust/noosphere-storage/src/implementation/memory.rs
rust/noosphere-storage/src/implementation/tracking.rs
rust/noosphere/Cargo.toml

replace lingering async-std usage with tokio, promote tokio/tokio-stream to workspace dependency, remove unused deps, a few anyhows weren't using workspace etc.

chore: Clean up redundant dependencies

---

Cargo.lock
Cargo.toml
rust/noosphere-cli/Cargo.toml
rust/noosphere-cli/tests/helpers/mod.rs
rust/noosphere-cli/tests/helpers/random.rs
rust/noosphere-cli/tests/peer_to_peer.rs
rust/noosphere-gateway/src/gateway.rs
rust/noosphere-ipfs/Cargo.toml
rust/noosphere-ns/Cargo.toml
rust/noosphere-sphere/src/sync/strategy.rs
rust/noosphere/src/ffi/mod.rs

This change increases our allowed body payload size to ~100MB. This is a stop-gap until such time as we update to streaming pushes (which can perhaps be treated in a special way). We also need to investigate:
- #606 
- #612
- #613

fix: Increase allowed request body payload size

---

rust/noosphere/Cargo.toml
rust/noosphere/tests/cli.rs
rust/noosphere/tests/distributed_basic.rs
rust/noosphere/tests/distributed_stress.rs
rust/noosphere/tests/gateway.rs

This is needed because `release-please` doesn't understand that a dependency cycle via `dev-dependencies` is permitted by Cargo. One could reasonably argue that this cycle is bad and should be resolved, but it's only for the sake of sharing test helpers and for now this is the path of least resistance.

chore: Trick `release-please` into accepting cycle

---

.github/workflows/container_images.yaml

We renamed this within the underlying infrastructure, so this should get things working correctly again.

chore: Update WIF provider name

---

Cargo.lock
rust/noosphere-collections/Cargo.toml
rust/noosphere-collections/src/hamt/node.rs
rust/noosphere-collections/src/hamt/pointer.rs

chore: use tokio::sync::OnceCell instead of async_once_cell::OnceCell.

---

Cargo.lock
Cargo.toml
rust/noosphere-gateway/Cargo.toml
rust/noosphere-gateway/src/worker/syndication.rs

(almost) drop-in replacement, let's see what tests have to say

feat: Replace wnfs-namefilter with deterministic-bloom. Fixes #626

---

.vscode/settings.json
Cargo.lock
rust/noosphere-core/src/view/mutation.rs
rust/noosphere-core/src/view/sphere.rs
rust/noosphere-core/src/view/timeline.rs
rust/noosphere-gateway/Cargo.toml
rust/noosphere-gateway/src/gateway.rs
rust/noosphere-gateway/src/lib.rs
rust/noosphere-gateway/src/worker/cleanup.rs
rust/noosphere-gateway/src/worker/mod.rs
rust/noosphere-gateway/src/worker/name_system.rs
rust/noosphere-gateway/src/worker/syndication.rs

This change proposes a form of incremental history compaction, the core of which is implemented in `Sphere`. Its only use at this time will be in the Noosphere Gateway, where it will be used to ensure that side-effects that cause history to accrue for the gateway's sphere do not result in unbounded version growth. As of this change, the gateway will attempt to compact its history once an hour. The compaction flattens all history since the last user sync point.

feat: History compaction for spheres and gateways

---

Cargo.lock
Cargo.toml
rust/noosphere-common/Cargo.toml
rust/noosphere-common/src/helpers/wait.rs
rust/noosphere-common/src/latency.rs
rust/noosphere-common/src/lib.rs
rust/noosphere-common/src/unshared.rs
rust/noosphere-core/Cargo.toml
rust/noosphere-core/src/context/cursor.rs
rust/noosphere-core/src/context/replication/mod.rs
rust/noosphere-core/src/context/replication/write.rs
rust/noosphere-core/src/context/sync/strategy.rs
rust/noosphere-core/src/helpers/context.rs
rust/noosphere-core/src/stream/car.rs
rust/noosphere-core/src/stream/ledger.rs
rust/noosphere-core/src/stream/mod.rs
rust/noosphere-core/src/view/sphere.rs
rust/noosphere-gateway/src/worker/syndication.rs
rust/noosphere-ipfs/examples/car.rs
rust/noosphere-ipfs/src/client/gateway.rs
rust/noosphere-ipfs/src/client/kubo.rs
rust/noosphere-ipfs/src/client/mod.rs
rust/noosphere-storage/Cargo.toml
rust/noosphere-storage/src/db.rs
rust/noosphere-storage/src/retry.rs
rust/noosphere/Cargo.toml
rust/noosphere/tests/distributed_basic.rs
rust/noosphere/tests/sphere_channel.rs

This change proposes the following:
- A "fall back to local data" strategy for peers with new versions that fail to replicate
- Per-block latency guards on CAR streams to detect stalled Kubo queries
- Secondary Kubo pinning for orphaned blocks in Noosphere CAR streams
- Timeouts when looking blocks up from Kubo have been reduced (net ~16s to net ~10s)
- Improvements to `car` example utility to report orphaned or missing blocks in a CARv1

feat: 3P replication fall-back and resilience

---

.github/workflows/report_test_flakes.yaml
.github/workflows/run_test_suite.yaml
images/orb/Dockerfile
rust/noosphere-core/src/api/client.rs
rust/noosphere-core/src/stream/memo.rs
rust/noosphere-core/src/view/content.rs
rust/noosphere-gateway/src/gateway.rs
rust/noosphere-gateway/src/handlers/v0alpha2/push.rs
rust/noosphere-gateway/src/worker/cleanup.rs
rust/noosphere-gateway/src/worker/name_system.rs
rust/noosphere-gateway/src/worker/syndication.rs
rust/noosphere-storage/examples/bench/main.rs
rust/noosphere-storage/src/retry.rs
rust/noosphere/tests/distributed_stress.rs

- Adds an automatic attempt by the gateway to syndicate to Kubo at startup and on a 5 minute interval
- Moves CI tests to `cargo-nextest` with `--retries 5` for relatively lenient flake allowance
- Makes logging in `orb` more verbose
- Rust test suite coverage expanded to include MacOS 13
We now have a Github Workflow that reports test flakes in test runs. The report looks like this:

feat: Periodic syndication checks to IPFS Kubo

---

.github/workflows/run_test_suite.yaml
Cargo.lock
rust/noosphere-gateway/src/handlers/v0alpha2/push.rs
rust/noosphere-ns/src/bin/orb-ns/main.rs
rust/noosphere/Cargo.toml
rust/noosphere/build.rs
rust/noosphere/src/ffi/mod.rs

Preparing with in-flight PR https://github.com/getditto/safer_ffi/pull/191.
~~There's a new clippy lint rule (documented as available since 1.72.0, though only appears in nightly channels), and some extra finesse on targeting nightly builds with a dynamic lint.~~ also fixed in latest safer_ffi
Other than that, just a lifetime change needed.

feat: Fix nightly builds and add to CI.

---

.github/workflows/run_test_suite.yaml

Not sure on how to test this, but builds on main are reporting as failing due to no corresponding issue to post a comment to

chore: Do not report flakes on main branch with no corresponding issue

---

rust/noosphere-core/Cargo.toml
rust/noosphere-core/src/api/client.rs

...when feature 'test-gateway' is enabled.

feat: Rewrite host headers in API client to embed sphere identity in subdomain

---

Cargo.lock
Cargo.toml
rust/noosphere-cli/Cargo.toml
rust/noosphere-cli/build.rs
rust/noosphere-cli/src/native/cli.rs
rust/noosphere-cli/src/native/mod.rs

This change proposes a new `orb version` command to help us track which version of the CLI is in use. It uses the [`vergen`](https://crates.io/crates/vergen) crate, which captures build-relevant environment information for later use in the final binary.
The output of the new command has two levels of verbosity. Simple:
```shell
❯ orb version
0.15.4
```
And verbose:
```shell
❯ orb version --verbose
Version (  orb): 0.15.4
Date (build): 2023-11-16
Timestamp (build): 2023-11-16T21:48:24.943980651Z
Debug (cargo): true
Features (cargo): default
Opt Level (cargo): 0
Target Triple (cargo): x86_64-unknown-linux-gnu
Branch (  git): fix/make-orb-render-good
Commit Author Email (  git): 0xcda7a@gmail.com
Commit Author Name (  git): Chris Joel
Commit Count (  git): 475
Commit Date (  git): 2023-11-16 …
```

feat: `orb version` command

---

.github/workflows/run_test_suite.yaml
typescript/package-lock.json
typescript/packages/sphere-viewer/package.json

Currently breaking [documentation generation](https://github.com/subconsciousnetwork/noosphere/actions/runs/7184283771/job/19564995592), which only runs on `main`. Added a `npm run build` before `npm run test` in the test runner to uncover issues before they hit main. Not sure how `npm run test` runs without a prior build step.

chore: Revert "chore(deps): bump @reduxjs/toolkit from 1.9.7 to 2.0.1 in /typescript (#743)"

---

rust/noosphere-core/Cargo.toml
rust/noosphere-core/src/api/client.rs

This reverts commit da912235ed3c5e1e3200110b98980fa393dbe91e.

chore: Revert "feat: Rewrite host headers in API client to embed sphere identity in subdomain when feature 'test-gateway' is enabled."

---

rust/noosphere-gateway/src/gateway.rs

Initializing tracing is the responsibility of a surrounding binary, not library code.

fix!: The gateway should not call initialize_tracing

---

rust/noosphere-core/src/tracing.rs

Allows exfiltration of instrumentation from noosphere into handy places like otel syncs like:
```rust
let tracer = opentelemetry_otlp::new_pipeline()
.tracing()
.with_trace_config(
trace::config().with_resource(Resource::new(vec![KeyValue::new(
"service.name",
"my service",
)])),
)
.with_exporter(opentelemetry_otlp::new_exporter().tonic())
.install_batch(opentelemetry_sdk::runtime::Tokio)?;
let otel = tracing_opentelemetry::layer().with_tracer(tracer);
initialize_tracing_with_layer(None, "multi-tenant gateway", otel);
```

feat: Add support for BYO tracing_subscriber

---

Cargo.lock
Cargo.toml
rust/noosphere-into/Cargo.toml
rust/noosphere-ipfs/Cargo.toml
rust/noosphere-ipfs/src/client/kubo.rs

[Issues with async-compat@0.2.3 in wasm32](https://github.com/subconsciousnetwork/noosphere/pull/695#issuecomment-1811621724), and this lets us continue using tokio-family crates.
Dependent on upstream subtext https://github.com/subconsciousnetwork/subtext/pull/59 landing
Fixes potentially multiple subtext instances (workspace consolidation)

chore: async compat to tokio utils

---

rust/noosphere-core/src/context/content/write.rs
rust/noosphere-core/src/context/context.rs
rust/noosphere-core/src/data/headers/header.rs
swift/Tests/SwiftNoosphereTests/NoosphereTests.swift

First pass on this; we could also add length when `link`ing, either the size of the pointer or `0`

feat: add Content-Length headers when writing to a sphere.

---

Cargo.lock
Cargo.toml
rust/noosphere-core/Cargo.toml
rust/noosphere-core/src/api/client.rs
rust/noosphere-core/src/api/headers/mod.rs
rust/noosphere-core/src/api/headers/ucan.rs
rust/noosphere-core/src/api/mod.rs
rust/noosphere-core/src/api/v0alpha1/data.rs
rust/noosphere-core/src/api/v0alpha2/data.rs
rust/noosphere-gateway/Cargo.toml
rust/noosphere-gateway/src/error.rs
rust/noosphere-gateway/src/extractors/authority.rs
rust/noosphere-gateway/src/extractors/cbor.rs
rust/noosphere-gateway/src/gateway.rs
rust/noosphere-gateway/src/handlers/v0alpha1/fetch.rs
rust/noosphere-gateway/src/handlers/v0alpha1/replicate.rs
rust/noosphere-gateway/src/handlers/v0alpha2/push.rs
rust/noosphere-into/examples/notes-to-html/implementation.rs
rust/noosphere-ns/Cargo.toml
rust/noosphere-ns/src/server/implementation.rs

* Updates Axum to 0.7, and its related crates. Removes `hyper` dependencies, several Axum generics, and uses Axum's new Body type. [Axum CHANGELOG](https://github.com/tokio-rs/axum/blob/main/axum/CHANGELOG.md)
* Handle different `StatusCode` implementations due to being pinned on `reqwest@0.11.20` #686, opting for `http@1`'s version (and Axum's).
* Update `axum-tracing-opentelemetry` to 0.16, the version compatible with Axum 0.7+

chore: Update axum 0.7

---

rust/noosphere-gateway/src/gateway.rs

The "did identity" route is not globally applicable, especially in cases where custom
GatewayManager implementations are in play.

feat: Add a healthcheck endpoint to the gateway.

---

.config/nextest.toml
.github/workflows/run_test_suite.yaml

Installing openssl via choco downloads an exe from slproweb.com:
```
openssl v3.2.0 [Approved]
openssl package files install completed. Performing other installation steps.
Attempt to get headers for https://slproweb.com/download/Win64OpenSSL-3_2_0.exe failed.
The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://slproweb.com/download/Win64OpenSSL-3_2_0.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading openssl 64 bit
from 'https://slproweb.com/download/Win64OpenSSL-3_2_0.exe'
```
Occasionally this site goes down. Other times it downloads the 200MB artifact @ 150kb/s, timing out the test. Attempt to use openssl built into GH runners.

chore: Use default openssl on github CI and do not fail early on tests

---

.github/workflows/run_test_suite.yaml
Cargo.lock
Cargo.toml
images/orb-ns/Dockerfile
images/orb/Dockerfile
rust/noosphere-core/Cargo.toml
rust/noosphere-ns/Cargo.toml
rust/noosphere-ns/src/builder.rs
rust/noosphere-ns/src/dht/config.rs
rust/noosphere-ns/src/dht/errors.rs
rust/noosphere-ns/src/dht/node.rs
rust/noosphere-ns/src/dht/processor.rs
rust/noosphere-ns/src/dht/swarm.rs
rust/noosphere-ns/src/utils.rs

One major need for this is to continue building on rust nightly 1.78.0, due to our current libp2p version using an incompatible crate in its dependency graph.
Docker images are also updated to rust stable (1.75.0) to support dependency updates.

chore: Update libp2p to 0.53.2

---

.github/workflows/run_test_suite.yaml

Erroneously introduced by applying #805 on inflight PRs to get tests running

chore: Remove duplicate continue-on-error

---

Cargo.lock
Cargo.toml
rust/noosphere-ipfs/Cargo.toml
rust/noosphere-ipfs/examples/car.rs

`multihash` is used by many of our dependencies (cid, libipld-*, libp2p) and there were some breaking changes in 0.19 (https://github.com/subconsciousnetwork/noosphere/pull/824) -- all of our usage of `multihash` is via `cid::multihash`, except in the single usage in an example where we use it directly. Continue using the version provided by `cid` (in sync with `libipld-*`)., as this is used throughout many dependencies, it's more important staying in sync than updating to the latest.

chore: Remove direct dependency to multihash -- use cid re-export instead

---

Cargo.lock
Cargo.toml
rust/noosphere-cli/Cargo.toml
rust/noosphere-core/src/api/client.rs
rust/noosphere-core/src/api/mod.rs
rust/noosphere-core/src/api/v0alpha1/data.rs
rust/noosphere-core/src/api/v0alpha2/data.rs
rust/noosphere-ipfs/Cargo.toml
rust/noosphere-ns/Cargo.toml

Cleans up a handful of duplicated transitive http dependencies and issues with using an "old" reqwest with newer axum and related http utils. Fixes #686

chore: Upgrade reqwest to 0.12, without macos-system-configuration. Fixes #686
